[project]
name = "regex-line-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "detect-secrets>=1.5.0",
    "pre-commit>=4.2.0",
    "pre-commit-hooks>=6.0.0",
]
